services:
  claude-code-api:
    image: harbor.vect.one/quantatrisk/cc-api:latest
    container_name: claude-code-api
    restart: unless-stopped
    ports:
      - "8088:8080"
    environment:
      - RUST_LOG=info
      - DATABASE_URL=sqlite:///app/data/claude.db
    env_file:
      - .env
    volumes:
      - ./config:/app/config
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s